"""Pydantic models for platform configuration with fail-fast validation."""

from .code import (
    AutomatedQualityCheckerAgentTools,
    BackendApiReviewerAgentTools,
    CodeCommandTools,
    CodeQualityReviewerAgentTools,
    CodingStandardsReviewerAgentTools,
    CommitCommandTools,
    CoderAgentTools,
    DatabaseReviewerAgentTools,
    DesignConformanceReviewerAgentTools,
    FrontendReviewerAgentTools,
    InfrastructureReviewerAgentTools,
    SpecAlignmentReviewerAgentTools,
)
from .core import AgentToolsModel, CommandToolsModel, PlatformModel, ToolReference
from .patch import PatchCommandTools, PatchPlannerAgentTools
from .phase import PhaseArchitectAgentTools, PhaseCommandTools, PhaseCriticAgentTools
from ..platform_selector import PlatformType
from .plan import (
    AnalystCriticAgentTools,
    DesignSyncCommandTools,
    PlanAnalystAgentTools,
    PlanCommandTools,
    PlanConversationCommandTools,
    PlanCriticAgentTools,
    StandardsCommandTools,
)
from .project import (
    LanguageStackProfile,
    LanguageTooling,
    PlanPlatformChangeRequest,
    PlanSetupRequest,
    PlanSetupWithRecommendationRequest,
    PlatformRequest,
    PlatformRequirements,
    ProjectConfig,
    ProjectStack,
    ProjectToolingConfig,
    TemplateGenerationRequest,
)
from .roadmap import (
    CreatePhaseAgentTools,
    PlanRoadmapAgentTools,
    PlanRoadmapCommandTools,
    RoadmapAgentTools,
    RoadmapCriticAgentTools,
)
__all__ = [
    'AgentToolsModel',
    'CommandToolsModel',
    'PlatformModel',
    'ProjectStack',
    'LanguageStackProfile',
    'LanguageTooling',
    'ProjectToolingConfig',
    'PlatformRequest',
    'PlatformRequirements',
    'PlanSetupRequest',
    'PlanSetupWithRecommendationRequest',
    'PlanPlatformChangeRequest',
    'TemplateGenerationRequest',
    'ProjectConfig',
    'ToolReference',
    'PhaseCommandTools',
    'PlanCommandTools',
    'PlanConversationCommandTools',
    'StandardsCommandTools',
    'DesignSyncCommandTools',
    'CodeCommandTools',
    'CommitCommandTools',
    'PatchCommandTools',
    'PlanRoadmapCommandTools',
    'PlanRoadmapAgentTools',
    'PhaseArchitectAgentTools',
    'PhaseCriticAgentTools',
    'CreatePhaseAgentTools',
    'CoderAgentTools',
    'AnalystCriticAgentTools',
    'PlanAnalystAgentTools',
    'PlanCriticAgentTools',
    'RoadmapAgentTools',
    'RoadmapCriticAgentTools',
    'AutomatedQualityCheckerAgentTools',
    'SpecAlignmentReviewerAgentTools',
    'DesignConformanceReviewerAgentTools',
    'CodeQualityReviewerAgentTools',
    'FrontendReviewerAgentTools',
    'BackendApiReviewerAgentTools',
    'DatabaseReviewerAgentTools',
    'InfrastructureReviewerAgentTools',
    'CodingStandardsReviewerAgentTools',
    'PatchPlannerAgentTools',
    'PlatformType',
]
